 on:
   push:
     branches:
       - master
 name: release-please
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.5.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: json-order
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn install
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn lint
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn test:ci
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn compile
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}